apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devsecops-project
  description: DevSecOps pipeline project

  annotations:
    github.com/project-slug: manjuappu1375/DevSecOps-Project

    backstage.io/kubernetes-label-selector: app=devsecops-project

spec:
  type: service
  lifecycle: production
  owner: user:default/guest
