apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevSecOps-Project
  annotations:
    github.com/project-slug: manjuappu1375/DevSecOps-Project
spec:
  type: service
  owner: user
  lifecycle: experimental
