apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevSecOps-Project
  labels:
    app: DevSecOps-Project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: DevSecOps-Project
  template:
    metadata:
      labels:
        app: DevSecOps-Project
    spec:
      containers:
      - name: DevSecOps-Project
        image: nasi101/DevSecOps-Project:latest
        ports:
        - containerPort: 80
